from pydantic import BaseModel, Field, model_validator
from typing import List, Dict, Any

class LineItem(BaseModel):
    part_name: str = Field(description="Name of the damaged part or labour category")
    category: str = Field(description="IMT Category (e.g., METAL, PLASTIC_RUBBER, GLASS, CONSUMABLE, LABOUR_PAINTING, MECHANICAL_EXCLUSION)")
    claimed_cost_inr: float = Field(description="The cost claimed by the garage")
    depreciation_percentage: float = Field(description="The applied depreciation percentage (0.0 to 100.0)")
    depreciation_amount_inr: float = Field(description="The calculated depreciation amount in INR")
    approved_cost_inr: float = Field(description="The final approved cost for this line item (claimed - depreciation)")
    reason: str = Field(description="Brief justification for the depreciation applied")

class ClaimSummary(BaseModel):
    total_claimed_inr: float = Field(description="Sum of all claimed costs")
    total_approved_inr: float = Field(description="Sum of all approved costs")
    total_depreciation_inr: float = Field(description="Sum of all depreciation amounts")

class FinalAssessment(BaseModel):
    claim_id: str = Field(description="Unique identifier for the claim")
    vehicle_age_years: float = Field(description="Age of the vehicle in years")
    policy_status: str = Field(description="Status of the policy verification (ACTIVE, EXPIRED, NOT_FOUND, UNKNOWN)")
    policy_message: str = Field(description="Detailed message from the policy verification gatekeeper")
    add_ons_detected: Dict[str, bool] = Field(description="Dictionary of detected add-ons like zero_depreciation, engine_protect")
    ncb_history_note: str = Field(description="Summary of historical NCB or past claims from memory")
    line_items: List[LineItem] = Field(description="Detailed breakdown of each part/labour assessment")
    
    # ADD THIS NEW FIELD:
    system_warnings: List[str] = Field(
        default_factory=list, 
        description="Warnings generated by the system regarding discrepancies between claim text and policy records"
    )
    
    summary: ClaimSummary = Field(description="Financial summary of the claim")

    @model_validator(mode='after')
    def check_math_parity(self) -> 'FinalAssessment':
        """
        GUARDRAIL: Ensures that the summary totals exactly match the sum of the line items.
        Prevents LLM hallucination of final totals.
        """
        calculated_claimed = sum(item.claimed_cost_inr for item in self.line_items)
        calculated_approved = sum(item.approved_cost_inr for item in self.line_items)
        calculated_depreciation = sum(item.depreciation_amount_inr for item in self.line_items)
        
        # Allow a tiny floating point tolerance (0.01 INR) to prevent float precision errors
        tolerance = 0.01
        
        if abs(self.summary.total_claimed_inr - calculated_claimed) > tolerance:
            raise ValueError(f"Math Parity Error: total_claimed_inr ({self.summary.total_claimed_inr}) does not match sum of line items ({calculated_claimed})")
            
        if abs(self.summary.total_approved_inr - calculated_approved) > tolerance:
            raise ValueError(f"Math Parity Error: total_approved_inr ({self.summary.total_approved_inr}) does not match sum of line items ({calculated_approved})")
            
        if abs(self.summary.total_depreciation_inr - calculated_depreciation) > tolerance:
            raise ValueError(f"Math Parity Error: total_depreciation_inr ({self.summary.total_depreciation_inr}) does not match sum of line items ({calculated_depreciation})")
            
        # Also check that claimed - depreciation == approved for the summary
        if abs((self.summary.total_claimed_inr - self.summary.total_depreciation_inr) - self.summary.total_approved_inr) > tolerance:
            raise ValueError("Math Parity Error: total_claimed - total_depreciation does not equal total_approved in summary")

        return self