import logging
from typing import Dict, Any
from pydantic import ValidationError

from src.guardrails.schemas import FinalAssessment

logger = logging.getLogger(__name__)

def validate_final_assessment(raw_assessment: Dict[str, Any]) -> FinalAssessment:
    """
    Validates the raw dictionary output from the Agent against the FinalAssessment schema.
    Acts as the final Guardrail before the data is sent to the UI or database.
    
    Args:
        raw_assessment: The dictionary generated by the LangGraph Agent.
        
    Returns:
        A validated FinalAssessment Pydantic model.
        
    Raises:
        ValueError: If the math parity or schema validation fails.
    """
    try:
        # This triggers the @model_validator check automatically
        validated_assessment = FinalAssessment(**raw_assessment)
        logger.info("✅ Final assessment passed all schema and math parity guardrails.")
        return validated_assessment
        
    except ValidationError as e:
        logger.error(f"❌ Guardrail Validation Failed: {e}")
        # Re-raise as a standard ValueError for the Agent/UI to handle cleanly
        raise ValueError(f"Assessment failed validation: {e}")